version: '3.8'

services:
  music-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-analyzer-pro
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./music_library.db:/app/music_library.db
      - ./resources:/app/resources
      - ./config.yaml:/app/config.yaml:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${MUSIC_LIBRARY_PATH:-~/Music}:/music:ro
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped

  # Optional: Database viewer
  adminer:
    image: adminer
    container_name: music-db-viewer
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
    volumes:
      - ./music_library.db:/var/www/html/music_library.db

volumes:
  music_data:
    driver: local